#!/usr/bin/env python3
"""Embeds a binary file as a C++ byte array, for build-time resources (the
bundled LumiDessin font) that a text-based embed like EmbedStdlibDocs.cmake
cannot carry. Invoked from CMake at configure time; not part of the CLI.

    scripts/embed_binary.py <input-file> <output-header> <array-name>
"""

import sys


def main() -> int:
    if len(sys.argv) != 4:
        print("usage: embed_binary.py <input-file> <output-header> <array-name>", file=sys.stderr)
        return 2

    input_path, output_path, array_name = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(input_path, "rb") as f:
        data = f.read()

    lines = []
    lines.append("// Generated by Lumiere build. Do not edit.")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("")
    lines.append("namespace lumiere")
    lines.append("{")
    lines.append(f"inline constexpr unsigned char {array_name}[] = {{")
    for i in range(0, len(data), 20):
        chunk = data[i : i + 20]
        lines.append("    " + ",".join(str(b) for b in chunk) + ",")
    lines.append("};")
    lines.append(f"inline constexpr std::size_t {array_name}_SIZE = sizeof({array_name});")
    lines.append("} // namespace lumiere")
    lines.append("")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
