# Embeds the stdlib documentation .lum files into a generated C++ header.
#
# The stdlib is authored once as real Lumière source files (stdlib/*.lum) with
# `///` doc comments. This script reads them at configure time and emits
# stdlib_docs.generated.hpp containing the source text of each file. The
# library then parses those embedded sources (lexer + parser only) to build the
# hover/completion documentation for native builtins.

set(STDLIB_DOC_DIR "${PROJECT_SOURCE_DIR}/stdlib")

# Fixed ordering keeps the generated header deterministic.
set(STDLIB_DOC_SOURCES
    core.lum
    maths.lum
    texte.lum
    chemin.lum
    aleatoire.lum
    fichier.lum
    temps.lum
    luminet.lum
    lumitest.lum
    collections.lum
)

set(STDLIB_DOC_GEN_DIR "${CMAKE_CURRENT_BINARY_DIR}/generated")
file(MAKE_DIRECTORY "${STDLIB_DOC_GEN_DIR}")

set(STDLIB_DOC_GENERATED "${STDLIB_DOC_GEN_DIR}/stdlib_docs.generated.hpp")

set(STDLIB_DOC_HEADER_BODY "// Generated by Lumiere build. Do not edit.\n")
string(APPEND STDLIB_DOC_HEADER_BODY "#pragma once\n\n")
string(APPEND STDLIB_DOC_HEADER_BODY "#include <string_view>\n\n")
string(APPEND STDLIB_DOC_HEADER_BODY "namespace lumiere {\n")
string(APPEND STDLIB_DOC_HEADER_BODY "    struct EmbeddedStdlibFile {\n")
string(APPEND STDLIB_DOC_HEADER_BODY "        std::string_view name;\n")
string(APPEND STDLIB_DOC_HEADER_BODY "        std::string_view source;\n")
string(APPEND STDLIB_DOC_HEADER_BODY "    };\n\n")
string(APPEND STDLIB_DOC_HEADER_BODY "    inline constexpr EmbeddedStdlibFile STDLIB_DOC_FILES[] = {\n")

foreach(doc_source IN LISTS STDLIB_DOC_SOURCES)
    set(STDLIB_DOC_PATH "${STDLIB_DOC_DIR}/${doc_source}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${STDLIB_DOC_PATH}")
    file(READ "${STDLIB_DOC_PATH}" STDLIB_DOC_CONTENT)
    string(APPEND STDLIB_DOC_HEADER_BODY "        { \"${doc_source}\", R\"LUMIERE_DOC(${STDLIB_DOC_CONTENT})LUMIERE_DOC\" },\n")
endforeach()

string(APPEND STDLIB_DOC_HEADER_BODY "    };\n\n")
string(APPEND STDLIB_DOC_HEADER_BODY "} // namespace lumiere\n")

file(WRITE "${STDLIB_DOC_GENERATED}" "${STDLIB_DOC_HEADER_BODY}")
